# Generated by Django 2.0.3 on 2019-03-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64)),
                ('address', models.CharField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=32)),
                ('email', models.CharField(default=None, max_length=64)),
                ('message', models.CharField(default=None, max_length=800)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
