# Generated by Django 2.2 on 2019-04-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20190429_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recaptcha_score',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
